### ISSUE TITLE
Rides list/save a ride

### ISSUE THREAD

**Issue by dw0111** [dw0111/capstone-project#1]
## Value Statement
As a rider, I would like a way to save my past rides and display them in a list.

## Description
![grafik](https://user-images.githubusercontent.com/77288570/110135491-e134c900-7dce-11eb-9eb0-6506216e8cbf.png)

## Acceptance criteria
- [x] There is a form for filling in ride data (see description)
- [x] Submitting the form saves the ride to local storage
- [x] There is an anti-chronological list with all past rides 

## Tasks

- [x] Write tests for AC
- [x] Install and implement storybook into project
- [x] Create basic structure and style
- [x] Add logic to save form to local storage on submit

## Complexity
3
