### ISSUE TITLE
Header component

### ISSUE THREAD

**Issue by dw0111** [dw0111/capstone-project#10]
## Value Statement
As a rider, I would like to see which site I'm on.

## Description
![grafik](https://user-images.githubusercontent.com/77288570/111135645-34500e00-857d-11eb-94c9-e0c49fd4618c.png)

## Acceptance criteria
- [x] There is a Header component which can be used on different sites
- [x] It is implemented on all sites

## Tasks
- [x] Create storybook
- [x] Create basic structure
- [x] Add logic to be able to pass the title
- [x] Add to all sites
- [x] Write tests

## Complexity
2
