### ISSUE TITLE
Add ride confirmation

### ISSUE THREAD

**Issue by dw0111** [dw0111/capstone-project#13]
## Value Statement
As a user, I would like to get a visible confirmation that a ride has been added.

## Description
wip

## Acceptance criteria
- [ ] When adding a ride to the list, a pop-up appears and disappears confirming the added ride

## Tasks

- [ ] Create storybooks
- [ ] Create basic structure
- [ ] Add logic for when it should appear

## Complexity
2
