### ISSUE TITLE
Show message when filtering and no rides are displayed

### ISSUE THREAD

**Issue by dw0111** [dw0111/capstone-project#14]
## Value Statement
As a user, I would like a visible warning when I selected a time frame in which no rides are available.

## Description
wip

## Acceptance criteria
- [ ] When filtering for a time frame in which no rides are available, show a message informing about it

## Tasks

- [ ] Create storybooks
- [ ] Create basic structure
- [ ] Add logic for when it should show

## Complexity
2
