### ISSUE TITLE
Track total

### ISSUE THREAD

**Issue by dw0111** [dw0111/capstone-project#2]
## Value Statement
As a rider, I would like to see how many km and hours I rode in total.

## Description
![grafik](https://user-images.githubusercontent.com/77288570/110136269-c7e04c80-7dcf-11eb-9e3a-444473feca78.png)

## Acceptance criteria
- [x] It shows an overview over total km and hrs ridden

## Tasks
- [x] Write tests
- [x] Create storybook
- [x] Create basic structure
- [x] Add logic to calculate totals

## Complexity
2
