### ISSUE TITLE
Filter total by time

### ISSUE THREAD

**Issue by dw0111** [dw0111/capstone-project#3]
## Value Statement
As a rider, I would like to filter my statistics by day, month or year.

## Description
![grafik](https://user-images.githubusercontent.com/77288570/110136623-31605b00-7dd0-11eb-9398-d9c1d7a9e312.png)

## Acceptance criteria
- [x] The totals page contains two dropdown menus
- [x] With these menus the rider can select a timeframe for which to display total km and hrs ridden

## Tasks
- [x] Write tests
- [x] Add dropdown menus
- [x] Add logic for choosing timeframe

## Complexity
5
