### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by dw0111** [dw0111/capstone-project#4]
## Value Statement
As a rider, I would like to switch between the different pages at will.

## Description
![grafik](https://user-images.githubusercontent.com/77288570/110136841-75ebf680-7dd0-11eb-8b45-3ceeb989240a.png)

## Acceptance criteria
- [x] There is a pop up menu
- [x] In the menu I can choose from the different available pages

## Tasks
- [x] Write tests
- [x] Create storybooks
- [x] Create basic structure
- [x] Add logic and style to make menu appear on click

## Complexity
3
