### ISSUE TITLE
Service overview for fork

### ISSUE THREAD

**Issue by dw0111** [dw0111/capstone-project#8]
## Value Statement
As a rider, I would like to when I will have to service my fork next time.

## Description
![grafik](https://user-images.githubusercontent.com/77288570/111131857-f81aae80-8578-11eb-9366-44f5b1ad586f.png)

## Acceptance criteria
- [x] There is a page to view service status
- [x] It displays the date of the last service and status bars for when the next service will be necessary
- [x] Progress is calculated on hours/km ridden since last service
- [x] Last service and service intervals are editable

## Tasks

- [x] Create storybooks
- [x] Create basic structure
- [x] Add logic for calculations
- [x] Add growing progressbar
- [x] Add edit-buttons
- [ ] Write tests

## Complexity
3
